// Mock data para afiliados - Dados fictícios para desenvolvimento

import type { Affiliate } from '@/types/affiliate';

export const mockAffiliates: Affiliate[] = [
  {
    id: '1',
    name: 'Afiliado Alpha',
    email: 'alpha@example.com',
    totalInvestment: 5512.08,
    registrations: 345,
    ftds: 16,
    deposits: 27,
    ggr: 4076.14,
    ngr: 4576.14,
    roi: 76.47,
    conversionRate: 4.64,
    ranking: 1,
    status: 'top',
  },
  {
    id: '2',
    name: 'Afiliado Beta',
    email: 'beta@example.com',
    totalInvestment: 0,
    registrations: 0,
    ftds: 2,
    deposits: 0,
    ggr: 0,
    ngr: 0,
    roi: 0,
    conversionRate: 0,
    status: 'average',
  },
  {
    id: '3',
    name: 'Afiliado Gamma',
    email: 'gamma@example.com',
    totalInvestment: 8152.90,
    registrations: 128,
    ftds: 40,
    deposits: 138,
    ggr: 8531.28,
    ngr: 6961.28,
    roi: -14.62,
    conversionRate: 31.25,
    ranking: 2,
    status: 'top',
  },
  {
    id: '4',
    name: 'Afiliado Delta',
    email: 'delta@example.com',
    totalInvestment: 5619.92,
    registrations: 491,
    ftds: 157,
    deposits: 317,
    ggr: 8531.28,
    ngr: 5681.28,
    roi: 1.09,
    conversionRate: 31.98,
    ranking: 3,
    status: 'top',
  },
];

